/*
 * generated by Xtext
 */
package no.hib.dpf.text;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DPFTextUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return no.hib.dpf.text.ui.internal.DPFTextActivator.getInstance().getInjector("no.hib.dpf.text.DPFText");
	}
	
}
