/*
 * generated by Xtext
 */
package no.hib.dpf.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 * File has been generated by XText. It is not need here.
 */
public class DPFTextRuntimeModule extends no.hib.dpf.text.AbstractDPFTextRuntimeModule {
 // not need here!
}
