/*
 * generated by Xtext
 */
package no.hib.dpf.text.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 * 
 * Generated by XText. Not used here. Maybe some of the work which is done in
 * no.hib.dpf.text.ui.contentassist.DPFTextProposalProvider could have been better implemented here.
 * 
 */
public class DPFTextScopeProvider extends org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider {

}
