/*
 * generated by Xtext
 */
package no.hib.dpf.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import no.hib.dpf.text.services.DPFTextGrammarAccess;

public class DPFTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DPFTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected no.hib.dpf.text.parser.antlr.internal.InternalDPFTextParser createParser(XtextTokenStream stream) {
		return new no.hib.dpf.text.parser.antlr.internal.InternalDPFTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DPFTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DPFTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
