/*
 * generated by Xtext
 */
package no.hib.dpf.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DPFTextAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("no/hib/dpf/text/parser/antlr/internal/InternalDPFText.tokens");
	}
}
