/*
 * generated by Xtext
 */
/*
 * generated by Xtext
 */
package no.hib.dpf.text.serializer;

/**
 * Not use here!
 */
public class DPFTextSyntacticSequencer extends AbstractDPFTextSyntacticSequencer {
}
